version: '2.5'
services:
  php:
    user: "${UID}:${GID}"
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    networks:
      - fs2net

  db:
    container_name: fs2db
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=fs2
      - POSTGRES_USER=fs2
      - POSTGRES_PASSWORD=19092015
    networks:
      - fs2net

networks:
  fs2net:
    driver: bridge